### ISSUE TITLE
Battery percentage for mouse, etc.

### ISSUE THREAD

**Issue by EgorMatirov** [papyros/qml-desktop#6]
Now battery percentage is not retrieved for mouse, keyboard, etc.
http://upower.freedesktop.org/docs/Device.html#Device:Percentage says that "This property is only valid if the property type has the value battery."
But, at least for my mouse (Logitech M185) this property is set correctly. Maybe we can use it for mouse\keyboard\etc? I can implement that if it's a correct solution.

**Comment by boghison** [comment]
@EgorMatirov This is implemented, look at the UPowerDevice class

**Comment by EgorMatirov** [comment]
@boghison as far I can see from this snippet, percentage is only set for "battery" type. But mouse and keyboard have another types, so percentage isn't set in this case.
```c++
 if (m_type == UPowerDeviceType::LinePower) {
        m_online = iface.property("Online");
} else if (m_type == UPowerDeviceType::Battery) {
        m_energy = iface.property("Energy");
        m_energyFull = iface.property("EnergyFull");
        m_energyEmpty = iface.property("EnergyEmpty");
        m_energyRate = iface.property("EnergyRate");
        m_timeToEmpty = iface.property("TimeToEmpty");
        m_timeToFull = iface.property("TimeToFull");
        m_percentage = iface.property("Percentage");
        m_state = iface.property("State");
        m_isRechargeable = iface.property("IsRechargeable");
        m_capacity = iface.property("Capacity");
    }
```

**Comment by boghison** [comment]
@EgorMatirov Oops, I overlooked that, if you want to, do a PR :)
